apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qatrial.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "qatrial.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.env.JWT_SECRET | b64enc | quote }}
  {{- if .Values.env.AI_PROVIDER_KEY }}
  AI_PROVIDER_KEY: {{ .Values.env.AI_PROVIDER_KEY | b64enc | quote }}
  {{- else }}
  AI_PROVIDER_KEY: {{ "" | b64enc | quote }}
  {{- end }}
