"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 12:20:27.363514
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('subject_uri', sa.String(length=500), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    sa.UniqueConstraint('hash', name=op.f('uq_audit_log_hash'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_subject_uri'), ['subject_uri'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('document_blob',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mime', sa.String(length=200), nullable=False),
    sa.Column('bucket', sa.String(length=100), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_blob')),
    sa.UniqueConstraint('sha256', name=op.f('uq_document_blob_sha256'))
    )
    op.create_table('document_dossier_template',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('mission_type', sa.Enum('AUDIT', 'COMMISSION_SECURITE', 'ACCOMPAGNEMENT', 'DOCUMENTATION', 'APPEL_OFFRES', 'CONFORMITE', 'AUTRE', name='missiontype', native_enum=False, length=32), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('required_doc_types', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_dossier_template')),
    sa.UniqueConstraint('code', name=op.f('uq_document_dossier_template_code'))
    )
    with op.batch_alter_table('document_dossier_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_dossier_template_mission_type'), ['mission_type'], unique=False)

    op.create_table('identity_organization',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('CLIENT', 'GSMS', 'PARTNER', name='organizationkind', native_enum=False, length=32), nullable=False),
    sa.Column('siren', sa.String(length=14), nullable=True),
    sa.Column('crm_company_ref', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_organization'))
    )
    op.create_table('identity_service_account',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('app', sa.Enum('crm', 'grace', 'qatrial', 'tenderai', 'eve', name='serviceapp', native_enum=False, length=32), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_service_account')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_identity_service_account_key_hash'))
    )
    op.create_table('identity_user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('oidc_subject', sa.String(length=200), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_user')),
    sa.UniqueConstraint('email', name=op.f('uq_identity_user_email'))
    )
    op.create_table('identity_site',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('erp_type', sa.String(length=10), nullable=True),
    sa.Column('erp_category', sa.String(length=10), nullable=True),
    sa.Column('igh_class', sa.String(length=10), nullable=True),
    sa.Column('geo', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['identity_organization.id'], name=op.f('fk_identity_site_organization_id_identity_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_site'))
    )
    with op.batch_alter_table('identity_site', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_site_organization_id'), ['organization_id'], unique=False)

    op.create_table('identity_workspace',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('PERMANENT', 'TEMPORARY', name='workspacekind', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='workspacestatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_from_mission_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['identity_organization.id'], name=op.f('fk_identity_workspace_organization_id_identity_organization')),
    sa.ForeignKeyConstraint(['site_id'], ['identity_site.id'], name=op.f('fk_identity_workspace_site_id_identity_site')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_workspace'))
    )
    with op.batch_alter_table('identity_workspace', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_workspace_organization_id'), ['organization_id'], unique=False)

    op.create_table('event_event',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('subject_uri', sa.String(length=500), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('causation_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_event_event_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_event'))
    )
    with op.batch_alter_table('event_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_event_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_event_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_event_subject_uri'), ['subject_uri'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_event_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_event_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('event_workflow_instance',
    sa.Column('definition', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('subject_uri', sa.String(length=500), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('waiting_for', sa.JSON(), nullable=False),
    sa.Column('timer_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_event_workflow_instance_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_workflow_instance'))
    )
    with op.batch_alter_table('event_workflow_instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_workflow_instance_definition'), ['definition'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_workflow_instance_subject_uri'), ['subject_uri'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_workflow_instance_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('identity_membership',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('owner', 'admin', 'manager', 'auditor', 'consultant', 'member', 'viewer', 'client_admin', 'client_member', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['identity_organization.id'], name=op.f('fk_identity_membership_organization_id_identity_organization')),
    sa.ForeignKeyConstraint(['user_id'], ['identity_user.id'], name=op.f('fk_identity_membership_user_id_identity_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_identity_membership_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_membership')),
    sa.UniqueConstraint('user_id', 'organization_id', 'workspace_id', name=op.f('uq_identity_membership_user_id'))
    )
    with op.batch_alter_table('identity_membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_membership_user_id'), ['user_id'], unique=False)

    op.create_table('mission_mission',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('AUDIT', 'COMMISSION_SECURITE', 'ACCOMPAGNEMENT', 'DOCUMENTATION', 'APPEL_OFFRES', 'CONFORMITE', 'AUTRE', name='missiontype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='missionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('origin', sa.Enum('intake', 'crm', 'manual', 'tender', name='missionorigin', native_enum=False, length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['identity_user.id'], name=op.f('fk_mission_mission_owner_id_identity_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_mission_mission_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_mission'))
    )
    with op.batch_alter_table('mission_mission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mission_mission_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('work_deadline',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('subject_uri', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.Enum('REGULATORY', 'CONTRACT', 'TENDER', 'ACTION', name='deadlinekind', native_enum=False, length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reminder_policy', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_work_deadline_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_deadline'))
    )
    with op.batch_alter_table('work_deadline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_deadline_subject_uri'), ['subject_uri'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_deadline_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('document_document',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'INGESTED', 'CLASSIFIED', 'ARCHIVED', name='documentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.Enum('upload', 'email', 'crm', 'grace', 'tender', 'tenderai', 'generated', name='documentsource', native_enum=False, length=32), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['mission_mission.id'], name=op.f('fk_document_document_mission_id_mission_mission')),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_document_document_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_document'))
    )
    with op.batch_alter_table('document_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_document_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_document_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_document_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('event_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='outboxstatus', native_enum=False, length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_event.id'], name=op.f('fk_event_outbox_event_id_event_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_outbox'))
    )
    with op.batch_alter_table('event_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_outbox_event_id'), ['event_id'], unique=False)

    op.create_table('mission_external_ref',
    sa.Column('mission_id', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('uri', sa.String(length=500), nullable=False),
    sa.Column('system', sa.String(length=30), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=False),
    sa.Column('status_snapshot', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['mission_mission.id'], name=op.f('fk_mission_external_ref_mission_id_mission_mission')),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_mission_external_ref_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_external_ref')),
    sa.UniqueConstraint('workspace_id', 'uri', name=op.f('uq_mission_external_ref_workspace_id'))
    )
    with op.batch_alter_table('mission_external_ref', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mission_external_ref_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mission_external_ref_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('mission_participant',
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('lead', 'contributor', 'client_contact', 'reviewer', name='participantrole', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['mission_mission.id'], name=op.f('fk_mission_participant_mission_id_mission_mission')),
    sa.ForeignKeyConstraint(['user_id'], ['identity_user.id'], name=op.f('fk_mission_participant_user_id_identity_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_participant')),
    sa.UniqueConstraint('mission_id', 'user_id', 'role', name=op.f('uq_mission_participant_mission_id'))
    )
    with op.batch_alter_table('mission_participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mission_participant_mission_id'), ['mission_id'], unique=False)

    op.create_table('tender_case',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('buyer', sa.String(length=300), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenderai_rfp_uri', sa.String(length=300), nullable=True),
    sa.Column('lexsocket_uri', sa.String(length=300), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.Enum('PENDING', 'GO', 'NO_GO', name='gonogo', native_enum=False, length=32), nullable=False),
    sa.Column('decision', sa.Enum('PENDING', 'GO', 'NO_GO', name='gonogo', native_enum=False, length=32), nullable=False),
    sa.Column('decided_by', sa.String(length=200), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['mission_mission.id'], name=op.f('fk_tender_case_mission_id_mission_mission')),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_tender_case_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tender_case')),
    sa.UniqueConstraint('mission_id', name=op.f('uq_tender_case_mission_id'))
    )
    with op.batch_alter_table('tender_case', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tender_case_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('work_finding_ref',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=True),
    sa.Column('source_uri', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'major', 'minor', 'info', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('control_ref', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['mission_mission.id'], name=op.f('fk_work_finding_ref_mission_id_mission_mission')),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_work_finding_ref_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_finding_ref'))
    )
    with op.batch_alter_table('work_finding_ref', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_finding_ref_source_uri'), ['source_uri'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_finding_ref_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('work_notification',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.Enum('inapp', 'email', name='notificationchannel', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_event.id'], name=op.f('fk_work_notification_event_id_event_event')),
    sa.ForeignKeyConstraint(['user_id'], ['identity_user.id'], name=op.f('fk_work_notification_user_id_identity_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_notification'))
    )
    with op.batch_alter_table('work_notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_notification_user_id'), ['user_id'], unique=False)

    op.create_table('document_link',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('target_uri', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document_document.id'], name=op.f('fk_document_link_document_id_document_document')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_link')),
    sa.UniqueConstraint('document_id', 'target_uri', name=op.f('uq_document_link_document_id'))
    )
    with op.batch_alter_table('document_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_link_document_id'), ['document_id'], unique=False)

    op.create_table('document_version',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('blob_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('uploaded_by', sa.String(length=200), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['blob_id'], ['document_blob.id'], name=op.f('fk_document_version_blob_id_document_blob')),
    sa.ForeignKeyConstraint(['document_id'], ['document_document.id'], name=op.f('fk_document_version_document_id_document_document')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_version')),
    sa.UniqueConstraint('document_id', 'n', name=op.f('uq_document_version_document_id'))
    )
    with op.batch_alter_table('document_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_version_document_id'), ['document_id'], unique=False)

    op.create_table('work_action',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=True),
    sa.Column('finding_ref_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'VERIFYING', 'CLOSED', 'CANCELLED', name='actionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Enum('critical', 'major', 'minor', 'info', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capa_required', sa.Boolean(), nullable=False),
    sa.Column('capa_uri', sa.String(length=500), nullable=True),
    sa.Column('verification_required', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_ref_id'], ['work_finding_ref.id'], name=op.f('fk_work_action_finding_ref_id_work_finding_ref')),
    sa.ForeignKeyConstraint(['mission_id'], ['mission_mission.id'], name=op.f('fk_work_action_mission_id_mission_mission')),
    sa.ForeignKeyConstraint(['owner_id'], ['identity_user.id'], name=op.f('fk_work_action_owner_id_identity_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_work_action_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_action'))
    )
    with op.batch_alter_table('work_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_action_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_action_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('work_evidence',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('target_uri', sa.String(length=500), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('by', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_version.id'], name=op.f('fk_work_evidence_document_version_id_document_version')),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_work_evidence_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_evidence'))
    )
    with op.batch_alter_table('work_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_evidence_target_uri'), ['target_uri'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_evidence_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('work_task',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=True),
    sa.Column('mission_id', sa.Uuid(), nullable=True),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'DOING', 'DONE', name='taskstatus', native_enum=False, length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['work_action.id'], name=op.f('fk_work_task_action_id_work_action')),
    sa.ForeignKeyConstraint(['assignee_id'], ['identity_user.id'], name=op.f('fk_work_task_assignee_id_identity_user')),
    sa.ForeignKeyConstraint(['mission_id'], ['mission_mission.id'], name=op.f('fk_work_task_mission_id_mission_mission')),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_work_task_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_task'))
    )
    with op.batch_alter_table('work_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_task_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_task_workspace_id'))

    op.drop_table('work_task')
    with op.batch_alter_table('work_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_evidence_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_work_evidence_target_uri'))

    op.drop_table('work_evidence')
    with op.batch_alter_table('work_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_action_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_work_action_mission_id'))

    op.drop_table('work_action')
    with op.batch_alter_table('document_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_version_document_id'))

    op.drop_table('document_version')
    with op.batch_alter_table('document_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_link_document_id'))

    op.drop_table('document_link')
    with op.batch_alter_table('work_notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_notification_user_id'))

    op.drop_table('work_notification')
    with op.batch_alter_table('work_finding_ref', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_finding_ref_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_work_finding_ref_source_uri'))

    op.drop_table('work_finding_ref')
    with op.batch_alter_table('tender_case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tender_case_workspace_id'))

    op.drop_table('tender_case')
    with op.batch_alter_table('mission_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mission_participant_mission_id'))

    op.drop_table('mission_participant')
    with op.batch_alter_table('mission_external_ref', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mission_external_ref_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_mission_external_ref_mission_id'))

    op.drop_table('mission_external_ref')
    with op.batch_alter_table('event_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_outbox_event_id'))

    op.drop_table('event_outbox')
    with op.batch_alter_table('document_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_document_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_document_document_mission_id'))
        batch_op.drop_index(batch_op.f('ix_document_document_doc_type'))

    op.drop_table('document_document')
    with op.batch_alter_table('work_deadline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_deadline_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_work_deadline_subject_uri'))

    op.drop_table('work_deadline')
    with op.batch_alter_table('mission_mission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mission_mission_workspace_id'))

    op.drop_table('mission_mission')
    with op.batch_alter_table('identity_membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_membership_user_id'))

    op.drop_table('identity_membership')
    with op.batch_alter_table('event_workflow_instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_workflow_instance_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_event_workflow_instance_subject_uri'))
        batch_op.drop_index(batch_op.f('ix_event_workflow_instance_definition'))

    op.drop_table('event_workflow_instance')
    with op.batch_alter_table('event_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_event_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_event_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_event_subject_uri'))
        batch_op.drop_index(batch_op.f('ix_event_event_mission_id'))
        batch_op.drop_index(batch_op.f('ix_event_event_correlation_id'))

    op.drop_table('event_event')
    with op.batch_alter_table('identity_workspace', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_workspace_organization_id'))

    op.drop_table('identity_workspace')
    with op.batch_alter_table('identity_site', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_site_organization_id'))

    op.drop_table('identity_site')
    op.drop_table('identity_user')
    op.drop_table('identity_service_account')
    op.drop_table('identity_organization')
    with op.batch_alter_table('document_dossier_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_dossier_template_mission_type'))

    op.drop_table('document_dossier_template')
    op.drop_table('document_blob')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_subject_uri'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
