"""document parse and workspace digest

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 10:47:59.787388
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest_workspace_digest',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('BUILT', 'FAILED', name='digeststatus', native_enum=False, length=32), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger', sa.String(length=200), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('conflict_count', sa.Integer(), nullable=False),
    sa.Column('missing_count', sa.Integer(), nullable=False),
    sa.Column('counts', sa.JSON(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['mission_mission.id'], name=op.f('fk_digest_workspace_digest_mission_id_mission_mission')),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_digest_workspace_digest_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_digest_workspace_digest'))
    )
    with op.batch_alter_table('digest_workspace_digest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digest_workspace_digest_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('document_parse',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PARSED', 'FAILED', name='parsestatus', native_enum=False, length=32), nullable=False),
    sa.Column('parser', sa.String(length=50), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('requested_by', sa.String(length=200), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document_document.id'], name=op.f('fk_document_parse_document_id_document_document')),
    sa.ForeignKeyConstraint(['mission_id'], ['mission_mission.id'], name=op.f('fk_document_parse_mission_id_mission_mission')),
    sa.ForeignKeyConstraint(['version_id'], ['document_version.id'], name=op.f('fk_document_parse_version_id_document_version')),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_document_parse_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_parse'))
    )
    with op.batch_alter_table('document_parse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_parse_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_parse_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_parse_version_id'), ['version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_parse_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_parse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_parse_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_document_parse_version_id'))
        batch_op.drop_index(batch_op.f('ix_document_parse_status'))
        batch_op.drop_index(batch_op.f('ix_document_parse_document_id'))

    op.drop_table('document_parse')
    with op.batch_alter_table('digest_workspace_digest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digest_workspace_digest_workspace_id'))

    op.drop_table('digest_workspace_digest')
    # ### end Alembic commands ###
