"""vault: encrypted blobs per workspace, folders, workspace keys

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-03

Après cette migration, ``python -m gsms_core.cli vault-migrate`` chiffre les fichiers existants par
workspace. Le downgrade échoue si un même fichier existe dans deux workspaces (unicité sha256 globale).
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_folder',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('system_key', sa.String(length=40), nullable=True),
    sa.Column('client_visible', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['vault_folder.id'], name=op.f('fk_vault_folder_parent_id_vault_folder')),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_vault_folder_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_folder'))
    )
    with op.batch_alter_table('vault_folder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vault_folder_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vault_folder_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('vault_workspace_key',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('wrapped_key', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_vault_workspace_key_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_workspace_key')),
    sa.UniqueConstraint('workspace_id', 'version', name=op.f('uq_vault_workspace_key_workspace_id'))
    )
    with op.batch_alter_table('vault_workspace_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vault_workspace_key_workspace_id'), ['workspace_id'], unique=False)

    with op.batch_alter_table('document_blob', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Uuid(), nullable=True))
        # Blobs existants : en clair (« none ») jusqu'à « gsms_core.cli vault-migrate ».
        batch_op.add_column(sa.Column('encryption', sa.String(length=40), nullable=False, server_default='none'))
        batch_op.add_column(sa.Column('key_version', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_document_blob_sha256'), type_='unique')
        batch_op.create_index(batch_op.f('ix_document_blob_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_blob_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_document_blob_workspace_id'), ['workspace_id', 'sha256'])
        batch_op.create_foreign_key(batch_op.f('fk_document_blob_workspace_id_identity_workspace'), 'identity_workspace', ['workspace_id'], ['id'])

    with op.batch_alter_table('document_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_document_document_folder_id'), ['folder_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_document_document_folder_id_vault_folder'), 'vault_folder', ['folder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_document', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_document_document_folder_id_vault_folder'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_document_document_folder_id'))
        batch_op.drop_column('folder_id')

    with op.batch_alter_table('document_blob', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_document_blob_workspace_id_identity_workspace'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_document_blob_workspace_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_document_blob_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_document_blob_sha256'))
        batch_op.create_unique_constraint(batch_op.f('uq_document_blob_sha256'), ['sha256'])
        batch_op.drop_column('key_version')
        batch_op.drop_column('encryption')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('vault_workspace_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vault_workspace_key_workspace_id'))

    op.drop_table('vault_workspace_key')
    with op.batch_alter_table('vault_folder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vault_folder_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_vault_folder_parent_id'))

    op.drop_table('vault_folder')
    # ### end Alembic commands ###
