"""communications: messages

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-03
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comm_message',
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('template', sa.String(length=60), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('external', sa.Boolean(), nullable=False),
    sa.Column('recipient_email', sa.String(length=320), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('TO_VALIDATE', 'QUEUED', 'SENT', 'FAILED', 'CANCELLED', name='messagestatus', native_enum=False, length=32), nullable=False),
    sa.Column('related_uri', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('validated_by', sa.String(length=200), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=300), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_comm_message_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comm_message')),
    sa.UniqueConstraint('reference', name=op.f('uq_comm_message_reference'))
    )
    with op.batch_alter_table('comm_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comm_message_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_comm_message_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comm_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comm_message_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_comm_message_status'))

    op.drop_table('comm_message')
    # ### end Alembic commands ###
