"""identité : équipe (accès par application, liens d'activation) et fournisseur OIDC

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-03 13:41:06.475414
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0009'
down_revision: str | None = '0008'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oidc_client',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('app', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), nullable=False),
    sa.Column('post_logout_redirect_uris', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('secret_rotated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('client_id', name=op.f('pk_oidc_client'))
    )
    op.create_table('identity_app_access',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('app', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity_user.id'], name=op.f('fk_identity_app_access_user_id_identity_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_app_access')),
    sa.UniqueConstraint('user_id', 'app', name=op.f('uq_identity_app_access_user_id'))
    )
    with op.batch_alter_table('identity_app_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_app_access_user_id'), ['user_id'], unique=False)

    op.create_table('identity_user_token',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('invitation', 'reset', name='usertokenpurpose', native_enum=False, length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity_user.id'], name=op.f('fk_identity_user_token_user_id_identity_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_user_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_identity_user_token_token_hash'))
    )
    with op.batch_alter_table('identity_user_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_user_token_user_id'), ['user_id'], unique=False)

    op.create_table('oidc_code',
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('redirect_uri', sa.String(length=500), nullable=False),
    sa.Column('scope', sa.String(length=200), nullable=False),
    sa.Column('nonce', sa.String(length=300), nullable=True),
    sa.Column('code_challenge', sa.String(length=128), nullable=True),
    sa.Column('auth_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['oidc_client.client_id'], name=op.f('fk_oidc_code_client_id_oidc_client')),
    sa.ForeignKeyConstraint(['user_id'], ['identity_user.id'], name=op.f('fk_oidc_code_user_id_identity_user')),
    sa.PrimaryKeyConstraint('code_hash', name=op.f('pk_oidc_code'))
    )
    with op.batch_alter_table('oidc_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oidc_code_expires_at'), ['expires_at'], unique=False)

    with op.batch_alter_table('identity_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_user', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')

    with op.batch_alter_table('oidc_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oidc_code_expires_at'))

    op.drop_table('oidc_code')
    with op.batch_alter_table('identity_user_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_user_token_user_id'))

    op.drop_table('identity_user_token')
    with op.batch_alter_table('identity_app_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_app_access_user_id'))

    op.drop_table('identity_app_access')
    op.drop_table('oidc_client')
    # ### end Alembic commands ###
