"""dossier AO : référence de workspace, statut du dossier, historique

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-03 16:34:46.289482
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0010'
down_revision: str | None = '0009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_status_change',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('DRAFT', 'REVIEW', 'READY', 'APPROVED', 'SUBMITTED', name='dossierstatus', native_enum=False, length=32), nullable=False),
    sa.Column('to_status', sa.Enum('DRAFT', 'REVIEW', 'READY', 'APPROVED', 'SUBMITTED', name='dossierstatus', native_enum=False, length=32), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['tender_case.id'], name=op.f('fk_tender_status_change_case_id_tender_case')),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_tender_status_change_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tender_status_change'))
    )
    with op.batch_alter_table('tender_status_change', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tender_status_change_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tender_status_change_workspace_id'), ['workspace_id'], unique=False)

    with op.batch_alter_table('identity_workspace', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=40), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_identity_workspace_reference'), ['reference'])

    with op.batch_alter_table('tender_case', schema=None) as batch_op:
        # Dossiers existants : brouillon (server_default nécessaire pour les lignes déjà présentes).
        batch_op.add_column(sa.Column('consultation_ref', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'READY', 'APPROVED', 'SUBMITTED', name='dossierstatus', native_enum=False, length=32), nullable=False, server_default='DRAFT'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender_case', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('consultation_ref')

    with op.batch_alter_table('identity_workspace', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_identity_workspace_reference'), type_='unique')
        batch_op.drop_column('reference')

    with op.batch_alter_table('tender_status_change', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tender_status_change_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_tender_status_change_case_id'))

    op.drop_table('tender_status_change')
    # ### end Alembic commands ###
