"""matrice d'exigences AO

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-03 16:56:42.981254
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0011'
down_revision: str | None = '0010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_requirement',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('digest_key', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('source', sa.JSON(), nullable=True),
    sa.Column('source_label', sa.String(length=300), nullable=True),
    sa.Column('planned_response', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('target_document', sa.String(length=20), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'COVERED', 'PARTIAL', 'BLOCKED', 'NOT_APPLICABLE', name='requirementstatus', native_enum=False, length=32), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['tender_case.id'], name=op.f('fk_tender_requirement_case_id_tender_case')),
    sa.ForeignKeyConstraint(['workspace_id'], ['identity_workspace.id'], name=op.f('fk_tender_requirement_workspace_id_identity_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tender_requirement')),
    sa.UniqueConstraint('case_id', 'code', name='uq_tender_requirement_code'),
    sa.UniqueConstraint('case_id', 'digest_key', name='uq_tender_requirement_digest_key')
    )
    with op.batch_alter_table('tender_requirement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tender_requirement_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tender_requirement_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender_requirement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tender_requirement_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_tender_requirement_case_id'))

    op.drop_table('tender_requirement')
    # ### end Alembic commands ###
