"""dossier AO : montant estimé

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-03 17:26:17.096097
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0012'
down_revision: str | None = '0011'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender_case', schema=None) as batch_op:
        batch_op.drop_column('estimated_amount')

    # ### end Alembic commands ###
